build:
dependencies:
    before:
        -
            command: "mkdir build"
nodes:
    coverage:
        tests:
            override:
            - command: "npm test"
                coverage:
                    file: "build/coverage.xml"
                        format: xml