filter:
    excluded_paths: [node_modules/*, build/*, lib/*]

build:
    dependencies:
        before:
            - npm install   # or add it as part of your package.json

    tests:
        override:
            -
                command: 'npm test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'